runtime: python310  # Use Python 3.10 or choose an appropriate version

env: flex

entrypoint: gunicorn -b :$PORT segmentation_project.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "segmentation_project.settings"

instance_class: F2  # Adjust depending on your resource requirements

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
  - url: /static
    static_dir: static/
  - url: /media
    static_dir: media/
  - url: /.*  # Catch-all handler to serve all other requests through Django
    script: auto

