# Generated by Django 5.1.2 on 2024-11-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('annual_income', models.FloatField()),
                ('spending_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('description', models.TextField()),
                ('avg_spending_score', models.FloatField(default=0.0)),
                ('avg_annual_income', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_segmentation.customerdata')),
            ],
        ),
    ]
