# Generated by Django 5.1.2 on 2024-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='cluster_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
